//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCEFC2024.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Courses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Courses()
        {
            this.Enrollments = new HashSet<Enrollments>();
        }
    
        public int CourseID { get; set; }
        [Required(ErrorMessage = "Ingrese el nombre por favor")]
        [MinLength(5)]
        public string Name { get; set; }

        [Required]
        public string Description { get; set; }
        [Required]
        public Nullable<int> Credit { get; set; }
        public string Nuevo { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Field { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enrollments> Enrollments { get; set; }
    }
}
